php:
  preset: laravel
  risky: true
  tab-width: 4
  use-tabs: false
  finder:
    exclude:
      - node_modules
      - public
      - vendor
    name: "*.php"
    not-name: "*.blade.php"
js:
  tab-width: 2
  use-tabs: false
  print-width: 80
  double-quotes: false
  trailing-commas: all
  semicolons: true
  arrow-parens: avoid
  bracket-spacing: true
  finder:
    exclude:
      - node_modules
      - public
    name:
      - "*.js"
      - "*.jsx"
    not-name:
      - "*.min.js"
