dist: trusty
language: php
sudo: required

php:
  - 7.1
  - 7.2
  - 7.3

addons:
   chrome: stable

cache:
  directories:
    - $HOME/.composer/cache

before_script:
   - travis_retry composer self-update
   - travis_retry composer install --no-interaction --prefer-dist --no-suggest
   - chmod -R o+w vendor/orchestra
   - sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
   - sudo apt-get -y install imagemagick x11-apps
   - export DISPLAY=:0.0
   - Xvfb :0 -screen 0 1920x1080x24 &
   
script:
   - vendor/bin/phpunit --coverage-clover=coverage.xml
  
after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - bliz48rus@gmail.com
      - salador2005@yandex.ru
    on_success: never
    on_failure: always
